swarm_sync_yml: |
  swarm-sync:
    stacks:
      - nonprod
    updateInterval: 60000
    git:
      url: https://github.com/swarm-pack/swarm-sync-example
      branch: master
    docker:
      socketPath: /var/run/docker.sock
    repositories:
      - name: official
        url: https://github.com/swarm-pack/repository